### ISSUE TITLE
Lib compatibility

### ISSUE THREAD

**Issue by aurelijusrozenas** [zenas1210/php-test-generator#1]
Hi,

you said you are planning to have lower php version just that this tool could be used in more projects. That's great!  
I just wanted to pinpoint that now this also is not installable for php 8 which probably is easily solved by composer constraint.
Another thing to keep in mind that other projects usually also use `phpdocumentor/reflection-docblock` and at least for couple of my projects the version (`^4.0`) was not compatible. It seems it is required by `symfony/serializer-pack` so it could pretty common usage amount symfony projects.

cheers!

**Comment by zenas1210** [comment]
Hi,
added compatibility for php 7.1 - 8.1, also replaced composer installation with a phar build (see readme) so there should be no more conflicts.
